apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:bsiS2JJNkPhFrVYWqO6jlsXNxuiSq/lb/8QIMUhGvLgOYLIJ8/4rfoJkJ93QaqT03pw9Qe02bt+/jzaUOlBl6Q==,iv:RlvT2G0cAQOEMIZvFrUY48q/ukCzV52NNQzzo2L1j3s=,tag:DusojaIZm7U+vY5sdmOesg==,type:str]
  username: ENC[AES256_GCM,data:XH+atRo=,iv:YI2wPnoo3ockw6gTtqHSRiV2NPARsON6HglKlnkdzMU=,tag:97RO8OuQ2Zw2lzRg637WCg==,type:str]
sops:
  age:
    - recipient: age1p54umg88pdhdt5m8zc69pfqcq08agav683vgqsp0zc8enrkg5g0skmgwv7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRWGRoTkhTZ0VBS3N0a1do
        alhZRDU3ODRrZ01GUGlHcHVOaTdpZ1B5OHlnCngrZktad1RycHRucCtqb2Ria3dV
        L3pabHZYdDRYTCtvWjgwRGpaYTNSUGMKLS0tIDVFMkdZNys2bVJ6TXFjUjdkYStV
        cUkySk5QQVE4VEQxVkJVK2VlbUlnOFkKKFXuqZjaCRw/jQ0F6BOrxsRkDIFBreEV
        VqYJz/TonUdai5zXcGB9OiJ7iM9Ptvl3GISJ6oh2Cd5Tm0DM5Vd9Xg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T00:05:00Z"
  mac: ENC[AES256_GCM,data:kw5Gib1PBLkESMwyZBDm8lvtzfVmt1PkSZwV/cmUD8qOA+3k4Rcuf9dhb/wBmtU0dz+AN3ZB2623fGFV3VZ97VWwWbHiCUkEQUR57qgrOftpvMa+9dinGTfFAVQz4dyIpBQ6gL+egIBTznGIYdAo75WMCVT1r+JRbzLqiFbw2ko=,iv:sThvx/8laUViVylk9jBuh+9fp4Ja5wzvVlljhdL8OlA=,tag:IpzS61EPb821MOBBm2w2zg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
