apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - alertmanager-certificate.yaml
  - alertmanager-ingressroute.yaml
  - grafana-certificate.yaml
  - grafana-ingressroute.yaml
  - prometheus-certificate.yaml
  - prometheus-ingressroute.yaml
  - release.yaml
  - repository.yaml
