---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: jellyfin
spec:
  scaleTargetRef:
    kind: Deployment
    name: jellyfin
  minReplicaCount: 0
  cooldownPeriod: 300
  triggers:
    - type: cron
      metadata:
        timezone: "Europe/Warsaw"
        start: "0 10 * * *"
        end: "0 2 * * *"
        desiredReplicas: "1"
