apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-appdata
  labels:
    app.kubernetes.io/instance: "bitwarden"
    app.kubernetes.io/name: "bitwarden"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
