apiVersion: v1
stringData:
    password: ENC[AES256_GCM,data:c85z5kWzaceCZGXnj7ONivIRMYjzVF4+nSw2otR4QTo=,iv:HdQdDFXDqZ3+vxj/uRIZ+MckT1E8D3epYDq1Ytvcfoo=,tag:zfwWtI7cmGnz86KmfdCmyA==,type:str]
    user: ENC[AES256_GCM,data:smgftJ0=,iv:aWDDn77Bfm0sSCHOBV7NUwzWF2tD5cZ6PGCFYSS5hOM=,tag:55zFud2z1T9VN2X78E62Mw==,type:str]
kind: Secret
metadata:
    name: paperless-admin-credentials
type: Opaque
sops:
    age:
        - recipient: age1p54umg88pdhdt5m8zc69pfqcq08agav683vgqsp0zc8enrkg5g0skmgwv7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiWGxBUjF6eGYzR1hEaEkr
            bUpJVkFucmxkd0V6VFJuL29kVGQ3UkN1T1FvCmQ5WnZFL2VkZW9UMlorcC82Tnlp
            LzNGOTAyT2JMaExpNjZYYmRjR1VQdWMKLS0tIExPbTVHZXJrUUI5SEhFWlVPSkIy
            b3hmS05zK3UzNWRxU0pSa0Vsc1h0aVEKki2mFWcJ2lodgsc5KbP4zzXWKvxVeHJu
            S4bp7mMQxggUoPSAdLJ0G/t6cs1v1PnAHy8d7rXwnogTHbN0aN1yKA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-20T03:09:33Z"
    mac: ENC[AES256_GCM,data:Lbeb2ob+MUWrmhKQS2Xh7XtCY4gaQQ/XPYwcu/+aD+QvMqU3yJo3G5FXungSLpVlI2gDjTq2UhvVSPTMfd4xeAz97BQA6uT/8HoDHmzPxhspznFMGtk2afn4uPoG2+fr8rf/0eK9XZzenJoivn6JMCSkbsXm77GASJ5cLIitFi0=,iv:oqU3KwR0aczhhqFf4HdxsaZrJj0C3cVOATbKQTzJyC4=,tag:dSGknboLPqhrQkpV2qIJ7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
