---
- name: Install prometheus node exporter
  ansible.builtin.apt:
    name: prometheus-node-exporter
    state: present
    update_cache: yes

- name: Ensure prometheus node exporter is enabled and running
  ansible.builtin.service:
    name: prometheus-node-exporter
    enabled: yes
    state: started
