apiVersion: cert-manager.io/v1
kind: Certificate
metadata: 
  name: ingressroute-certificate
spec:
  secretName: certificate-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames: 
    - immich.kube-01.home.majabojarska.dev
    - immich.home.majabojarska.dev