# https://truecharts.org/charts/stable/miniflux/
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: miniflux
spec:
  interval: 60m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://oci.trueforge.org/truecharts/miniflux
  ref:
    tag: 17.15.0
