apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-cnpg-main-user
spec:
  refreshInterval: "24h"
  target:
    name: miniflux-cnpg-main-user
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "miniflux"
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux-cnpg-main-urls
spec:
  refreshInterval: "24h"
  target:
    name: miniflux-cnpg-main-urls
    creationPolicy: Owner
    template:
      data:
        std: "postgresql://miniflux:{{ .password }}@miniflux-cnpg-main-rw:5432/miniflux"
        nossl: "postgresql://miniflux:{{ .password }}@miniflux-cnpg-main-rw:5432/miniflux?sslmode=disable"
        porthost: "miniflux-cnpg-main-rw:5432"
        host: "miniflux-cnpg-main-rw"
        jdbc: "jdbc:postgresql://miniflux-cnpg-main-rw:5432/miniflux"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
