# https://truecharts.org/charts/stable/changedetection-io/
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: changedetection-io
spec:
  interval: 60m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://oci.trueforge.org/truecharts/changedetection-io
  ref:
    tag: 5.19.1
