# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-af1757e6-0789-4cd6-99aa-311e7b6ae5cf";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-af1757e6-0789-4cd6-99aa-311e7b6ae5cf".device = "/dev/disk/by-uuid/af1757e6-0789-4cd6-99aa-311e7b6ae5cf";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CB58-531A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
