# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  boot = {
    initrd = {
      availableKernelModules =
        [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ ];
    extraModulePackages = [ ];

    # Bootloader.
    loader.grub = {
      enable = true;
      device = "/dev/sda";
      useOSProber = true;
    };

    supportedFilesystems = [ "zfs" ];
    zfs.extraPools = [ "storage" ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/bc27a2e4-0862-4363-a234-c03c335470fc";
    fsType = "ext4";
  };

  fileSystems."/mnt/hdd-01" = {
    device = "/dev/disk/by-uuid/27099cf4-357e-4f71-bd85-c6ab83c613b2";
    fsType = "ext4";
    options = [
      "noatime"
      "users" # Allows any user to mount and unmount
      "nofail" # Prevent system from failing if this drive doesn't mount
    ];
  };

  swapDevices = [ ];

  powerManagement.powertop.enable = true;
  powerManagement.cpuFreqGovernor = "conservative";

  networking = {
    domain = "home.majabojarska.dev";
    hostName = "nas";
    hostId = "53423d02"; # First 8 chars from /etc/machine-id

    networkmanager.enable = true;
    useDHCP = lib.mkDefault true;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
