apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./traefik
  - ./flannel
  - ./cert-manager
  - ./cloudnative-pg
  - ./metrics-server
  - ./monitoring
  - ./reloader
  - ./keda
  - ./intel-device-plugins-operator
  - ./node-feature-discovery
