apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiomuse-ai
resources:
  - ./namespace.yaml
  - ./password-gen.yaml
  - ./secret.yaml
  - ./cnpg-cluster.yaml
  - ./repository.yaml
  - ./release.yaml
  - ./certificate.yaml
  - ./ingressroute.yaml
