apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: audiomuse-ai-ingress
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: audiomuse-ai
      app.kubernetes.io/name: audiomuse-ai
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: traefik
      ports:
        - protocol: TCP
          port: 8000
