apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: audiomuse-cnpg
spec:
  refreshInterval: "24h"
  target:
    name: audiomuse-ai
    creationPolicy: Merge
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .password }}"
        pgpass: "audiomuse-rw:5432:app:app:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://audiomuse-rw.default:5432/app?password={{ .password }}&user=app"
        uri: "postgresql://app:{{ .password }}@audiomuse-rw.default:5432/app"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
