apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: audiomuse-cnpg
spec:
  refreshInterval: "24h"
  target:
    name: audiomuse-ai
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        POSTGRES_USER: "audiomuse"
        POSTGRES_PASSWORD: "{{ .password }}"
        POSTGRES_DB: "audiomuse"
        username: "audiomuse"
        password: "{{ .password }}"
        pgpass: "audiomuse-ai-rw:5432:audiomuse:audiomuse:{{ .password }}"
        jdbc-uri: "jdbc:postgresql://audiomuse-ai-rw.default:5432/audiomuse?****** .password }}&user=audiomuse"
        uri: "postgresql://audiomuse:{{ .password }}@audiomuse-ai-rw.default:5432/audiomuse"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: pg-password-generator
