---
- name: Get K3s kubeconfig
  ansible.builtin.command: 'k3s kubectl config view --raw'
  become: true
  register: k3s_config_exec
  changed_when: false

- name: Save kubeconfig to file
  delegate_to: localhost
  ansible.builtin.copy:
    # Assumes the apiserver is exposed on the same port externally, as locally.
    content: "{{ k3s_config_exec.stdout | ansible.builtin.regex_replace('(\\s+server: https://).+(:\\d+)', '\\1' + ansible_host + '\\2') }}"
    dest: '{{ playbook_dir }}/kubeconfig.yaml'
    mode: '0644'
  tags:
    - skip_ansible_lint
