apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingressroute-certificate
spec:
  secretName: certificate-secret
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - n8n.kube-01.home.majabojarska.dev
    - n8n.home.majabojarska.dev
