# https://truecharts.org/charts/stable/n8n/
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: n8n
spec:
  interval: 60m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://oci.trueforge.org/truecharts/n8n
  ref:
    tag: 18.18.1
