apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/platform
  - ./cluster-issuer.yaml
  - ./ovh-credentials.yaml
patches:
  - path: ./webhook-ovh-values.yaml
  - path: ./traefik-values.yaml
