apiVersion: v1
kind: Secret
metadata:
  name: ovh-credentials
  namespace: cert-manager
type: Opaque
stringData:
  applicationKey: ENC[AES256_GCM,data:m85MPs+emacmbWhvNgY/3g==,iv:MYMItwgJwJEDYLES/txe1TGzrbYw82O2LHTIN3H769w=,tag:B1U8tViQSmRMC+4DJc53fA==,type:str]
  applicationSecret: ENC[AES256_GCM,data:PJVyKO+kvzpfz23Fu92VTOWiXlgVs2mt5s13RLEYSn0=,iv:XkB9Z8PLYF10HhAu0bQ2vsxRCRXhez1McxE7KUU9nxs=,tag:8Yg0QP8/lj/ALEZAx4B20A==,type:str]
  consumerKey: ENC[AES256_GCM,data:QBm8hBexpHh8YsELSkYHsimEAMt9hSyd38jRk/xxmqU=,iv:ZE4NYQtRALjh3oB1XfGDPhki8gaoEgPBbce9JiSzFB8=,tag:LKE69Ahk9+BkuUQDq+rZ5w==,type:str]
sops:
  age:
    - recipient: age1p54umg88pdhdt5m8zc69pfqcq08agav683vgqsp0zc8enrkg5g0skmgwv7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVDQyODhwMnMvbFR6WVA1
        YlNlMXFKVkhSdlZQdFYvTExsYzl5aXBZdGlnCkxRWjVBWUUvVWphZEZsTlVDYUVj
        d2dZT0VpUWpuV2g4YTRtdUZFYVRJWmcKLS0tIDVJdnVFQ2luaDVnd0N6S2k2amc2
        U2xIK2g1ckl0UHFkTnZIOG1DbWw5a2cKcVxmU2uyiJ/QcSf17VN8yr+L1JZ4qmGU
        H2JzcPQUE9U6lNQpIbm+BYHGSpLZL6qkwYmTDrbUk3lQSGEw+R3BIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-20T02:23:25Z"
  mac: ENC[AES256_GCM,data:CIlhSBYauIrG+A/wHMFZGeli2Jzv3h0mX321T58Z7VXqL2zcvwVP+uyo/0Y+zsKI+mk4FUavtd9Y8qcpvpilVN1vjMUYzGtHeTjj9pOW6BUCBrWi/39dgl18d5lyuHRnfkY4bl9BkFK3gcyNfWXY2+BchxOkuh+B0GL6PA2hBvk=,iv:mUjfxkL5rBqexqSmLNO3Y3D99DAVKgGgjKgK9DZEqR0=,tag:h0GtY3OZ2hKT/NALlGzr2g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
