# Qbittorrent

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent
  namespace: traefik
spec:
  secretName: qbittorrent-tls
  dnsNames:
    - qbittorrent.home.majabojarska.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-systemd
  namespace: traefik
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: qbittorrent-systemd
  namespace: traefik
  labels:
    kubernetes.io/service-name: qbittorrent-systemd
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.1.30
ports:
  - name: http
    protocol: TCP
    port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbittorrent.home.majabojarska.dev`)
      kind: Rule
      services:
        - name: qbittorrent-systemd
          port: 8080
  tls:
    secretName: qbittorrent-tls
---

# Paperless

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: paperless
  namespace: traefik
spec:
  secretName: paperless-tls
  dnsNames:
    - paperless.home.majabojarska.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-systemd
  namespace: traefik
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: paperless-systemd
  namespace: traefik
  labels:
    kubernetes.io/service-name: paperless-systemd
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.1.30
ports:
  - name: http
    protocol: TCP
    port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paperless.home.majabojarska.dev`)
      kind: Rule
      services:
        - name: paperless-systemd
          port: 8080
  tls:
    secretName: paperless-tls
---

# Immich

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich
  namespace: traefik
spec:
  secretName: immich-tls
  dnsNames:
    - immich.home.majabojarska.dev
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
---
apiVersion: v1
kind: Service
metadata:
  name: immich-systemd
  namespace: traefik
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: immich-systemd
  namespace: traefik
  labels:
    kubernetes.io/service-name: immich-systemd
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.1.30
ports:
  - name: http
    protocol: TCP
    port: 8080
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`immich.home.majabojarska.dev`)
      kind: Rule
      services:
        - name: immich-systemd
          port: 8080
  tls:
    secretName: immich-tls
---
