apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  releaseName: frigate
  chartRef:
    kind: OCIRepository
    name: frigate
  interval: 60m
  install:
    remediation:
      retries: 3

  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                LIBVA_DRIVER_NAME: "iHD"
              fixedEnv:
                TZ: "Europe/Warsaw"

    persistence:
      # For HW accel
      dev-dri:
        enabled: true
        type: hostPath
        mountPath: /dev/dri
        hostPath: /dev/dri
        hostPathType: Directory

      config:
        enabled: true
        retain: true
        mountPath: /config
        storageClass: "local-path-zfs"
        accessMode: ReadWriteOnce
        size: 1Gi

      media:
        enabled: true
        retain: true
        mountPath: /media
        storageClass: "local-path-zfs"
        accessMode: ReadWriteOnce
        size: 100Gi

    securityContext:
      pod:
        supplementalGroups:
          - 303 # render
          - 26 # /dev/dri/card*
          - 17 # sound
      fsGroupChangePolicy: "OnRootMismatch"
