---
all:
  hosts:
    kube-01:
    nas:
    pve-01:
    pve-02:
    sp6cat-01:

nixos:
  hosts:
    kube-01:
    nas:
    sp6cat-vm-01:

debian:
  hosts:
    # rpi-3b:
    pve-01:
    pve-02:
    sp6cat-01:

pve:
  hosts:
    pve-01:
    pve-02:
    sp6cat-01:
