apiVersion: v1
kind: Secret
metadata:
  name: renovate
type: Opaque
stringData:
  #ENC[AES256_GCM,data:tdn3I5tA9XUMCqMfp/64/YORF4VNIUlq0qF1kOFR4Uxj/WXZow==,iv:tM36WYtpKCK84g5AhbTUwzX+hail0k/6924+6exQxJ8=,tag:/51GA2+vfsPfUnT5JITmgQ==,type:comment]
  RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:gEv9ae37KFisSiRaRzGOGudxTAWK16PmWrtoR1y/qc0DC32CpqBEymqvW6bZH1de086o0vzt/SBpRaCqsA1DCsgGL0zEWKlpXa6PoF7j2Z3UyEf2WxqCetFInmo5,iv:pFch3mtXyLOg9A5H1oq/oaIh1Tz+Ua6yaBNrho7Fz3Q=,tag:rx6SqEDPGtGNHJOJ7TRI3Q==,type:str]
  #ENC[AES256_GCM,data:qIIXoW2iIj3zgD8/xeUsNOv5b6rMvs7evjNJYNKn4crFUAaK30TEfCywIYU1Lo9eTiQbtO0e43c0JUkm,iv:+3EANBJ0Hv6grOy+wciN3kMYgBVFgWUnWXOKzXkBrL4=,tag:xVQyTPRsRLUhabhn+j3Cmw==,type:comment]
  RENOVATE_TOKEN: ENC[AES256_GCM,data:/rw8macgL44lU9BKeW/M/Jn7ATaVK5LT4Xvsz6GeV9rbCZ9yWFh3u1bBBgs0Am72S37i1H0y4KM3g1l1Q/0C+QMAcjmyhC9aLTOf+bVn3f3GmP3H7D+Dl5EwdaCO,iv:5IlG1bw4lclofQz2j3Y+4QWukuRYDMobJ7kxREe5jfQ=,tag:IvUh8UE5EXuBXqggzKF6gw==,type:str]
sops:
  age:
    - recipient: age1p54umg88pdhdt5m8zc69pfqcq08agav683vgqsp0zc8enrkg5g0skmgwv7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RnB6cUh3eUxETkJuRGtz
        WHR1TGU5K1FWb0wrQ0NLOUVpV2VFZXQ5UVFBClJhN3dTTTR5MnFrODdFUUNyRnUr
        SkF4SkczK0RVWUovRGVhSXNkTDJwNjgKLS0tIDRlc1c0eTBCQUZhYmc1ako4cUNP
        elZ3NlpXZkQ0b0FPajl3WDhKaXE1blUK/D2iNM2kw3tak+NNlVwB7OYYGaFNLl9m
        iHxHMWknGOpylnYSSrMgcLxxI0aSU0GuXvj8XPFrOhispAh2KleQeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-29T00:39:44Z"
  mac: ENC[AES256_GCM,data:vGqLBii3jb0JSywd/BCx+T4xWb0cnH+5ejW/ENdMQHIrp4XGPMTqhIXFGmh7HZ36cvMo0pPqYgvF262y4h6BCxacYMltyGg67mu/qk4cdbUpd69uf1oUaf1FyaGUpoJeMIXlKFNpRdiHU0n9uYLPx/+09hdx++b9egGhHhEZvew=,iv:ZA29F3nMZqF02WsrHG4flWTDAxI1IrUD6XOCDYCyIYE=,tag:OMaHZDxScj5XtB2GtdwXxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
