apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  releaseName: authentik
  chartRef:
    kind: OCIRepository
    name: authentik
  interval: 60m
  install:
    remediation:
      retries: 3
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              fixedEnv:
                TZ: "Europe/Warsaw"
              env:

    ingress:
      main:
        enabled: true
        hosts:
          - host: authentik.home.majabojarska.dev
            paths:
              - path: /
                pathType: Prefix
                overrideService:
                  name: main
                  port: 80
        tls:
          - hosts:
              - chart-example.local
            secretName: chart-example-tls
            # OR
            certificateIssuer: ""

    securityContext:
      pod:
        fsGroup: 10001 # kubernetes GID
        fsGroupChangePolicy: "OnRootMismatch"
