# https://truecharts.org/charts/stable/authentik/
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: authentik
spec:
  interval: 60m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://oci.trueforge.org/truecharts/authentik
  ref:
    tag: 34.4.0
