---
- name: Nix flake update
  ansible.builtin.shell:
    cmd: "nix flake update --flake '{{ role_path }}/nix'"
  delegate_to: localhost

- name: Make sure that the configuration directory exists
  ansible.builtin.file:
    path: "{{ flake_dir }}"
    owner: "{{ username }}"
    group: "{{ usergroup }}"
    state: directory
    mode: "0755"

- name: Populate configuration tree
  ansible.posix.synchronize:
    src: "{{ role_path }}/nix/"
    dest: "{{ flake_dir }}/"
    delete: true
    recursive: true

- name: NixOS build flake
  become: true
  ansible.builtin.shell:
    cmd: "nixos-rebuild build --flake {{ flake_dir }}#{{ inventory_hostname }}"

- name: NixOS test flake
  become: true
  ansible.builtin.shell:
    cmd: "nixos-rebuild test --flake {{ flake_dir }}#{{ inventory_hostname }}"

- name: NixOS rebuild from flake
  become: true
  ansible.builtin.shell:
    cmd: "nixos-rebuild switch --flake {{ flake_dir }}#{{ inventory_hostname }}"
