apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - ../base/authentik

  - ../base/paperless-ngx
  - ../base/immich
  - ../base/actualserver
  - ../base/jellyfin
  - ../base/frigate
  - ../base/qbittorrent

  - ../base/n8n

  - ../base/searxng

  - ../base/changedetection-io

  - ../base/renovate
  - ../base/miniflux

  - ../base/influxdb
  - ../base/booklore
