apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: 87.21.0
  values:
    additionalPrometheusRulesMap:
      {}
      #  rule-name:
      #    groups:
      #    - name: my_group
      #      rules:
      #      - record: my_record
      #        expr: 100 * my_record

    grafana:
      enabled: false

    prometheus:
      enabled: true
      prometheusSpec:
        remoteWrite:
          # - url: "http://sp6cat-vm-01.hswro.majabojarska.dev:someport/api/v1/write"
        storageSpec: {}
        retention: 1h
        retentionSize: "1GB"

    alertmanager:
      enabled: false
      monitor:
        enabled: false

    alertmanagerSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "local-path-zfs"
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi

  interval: 60m
  install:
    remediation:
      retries: 3
