name: "Dependencies"
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  nix-flake-update:
    name: Nix Flake update
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-25.11

      - name: Update nix flakes
        run: nix flake update --flake ./ansible/roles/majabojarska.nixos/nix

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: Update Nix Flake
          branch: chore/update-nix-flake
          delete-branch: true
          title: "Update Nix Flake"
          body: |
            ## Beep boop 🤖. Fresh Nix Flake incoming ♻️!

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request#
          labels: |
            dependencies
          draft: false
